### ISSUE TITLE
AWS Instances Keep Spinning Up Even After Termination

### ISSUE THREAD

**Issue by tanakamapondera** [hashicorp/learn-terraform-provision-eks-cluster#15]
![training](https://user-images.githubusercontent.com/43476830/91047718-83861f80-e5e8-11ea-874d-f2d0eac1384f.PNG)

I was using this repository to spin up Kubernetes on AWS last week but I was having an issue executing the provided terraform script. It would keep timing out before everything was completed.

At the time I thought nothing of it but turns out it was still creating worker groups on my AWS account. Every time I terminate the instances, they just spin up again a few seconds later. I searched google and can't seem to find the root of my issue. 

If anyone has come across this issue and may know how to stop this from happening, then I would really appreciate any and all the help that I can get!

**Comment by im2nguyen** [comment]
Thanks for bringing this up. It seems like you're trying to manually destroy instances spun up by an [autoscaling group](https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroup.html) instead of destroying the autoscaling group itself.

Have you tried running `terraform destroy`? That should destroy all the resources provisioned by this configuration.
