### ISSUE TITLE
please add examples for adding windows worker node

### ISSUE THREAD

**Issue by alnhk** [hashicorp/learn-terraform-provision-eks-cluster#24]
Hello.,

With help of this EKS terraform examples, we were able to provision the large scale DEV, STAGING and PRODUCTION AWS EKS environment, however, please add the examples on adding windows worker node to existing AWS EKS clusters. 

Like, using "eks-worker" along with nodegroup  configured for linux ,we are able to provision linux based worker, however for windows, did googled everywhere, it has "eks-worker-windows" or "eks_worker_windows" configured along with custom nodegroup for windows support., needs nodegroup for windows as well as eks worker windows related examples so that best practice can be followed.

This is appreciated.

**Comment by BrianMMcClain** [comment]
Hi @alnhk! Sorry this issue never got addressed. I'm going through and cleaning up this repo and did a bit of looking around on this one. It looks like Windows support has been greatly improved since this issue was opened. I'd recommend checking out some of the conversation in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2350 -- there's some great examples discussed in that issue.
