### ISSUE TITLE
Issue deploying the nodegroup

### ISSUE THREAD

**Issue by jjulianprin** [hashicorp/learn-terraform-provision-eks-cluster#25]
Hello.

After implementing this lab following the instructions (i only changed the region on the vpc.tf to use us-west-2) i have noticed there are not node groups associated to the EKS cluster (checking on the AWS management console). The instances are correctly listed on the AWS EC2 Management Console but not related to the cluster on the EKS Console.
Also, when running "kubectl get nodes -A " there are not nodes listed nor related to the cluster.

Finally, i tried moving ahead and deploy the metrics server on the cluster, running "kubectl apply -f metrics-server-0.3.6/deploy/1.8+/" (after downloading the package) and when running "kubectl get deployment metrics-server -n kube-system" the output is 
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
metrics-server   0/1     1            0           79s

i waited a long time but the deployment is never getting deployed because there are no nodes attached to the cluster

kubectl get nodes
No resources found

PS. i've been trying to perform the same eks cluster launch from within AWS Management Console and it is failing with "instances failed to join the kubernetes cluster" everytime i create a node group, even if i am using the cloudformation templates given here. https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html i just mention this to keep in mind maybe this could be an AWS bug.

**Comment by ashwajce** [comment]
Same here I'm also seeing the same behaviour

**Comment by jjulianprin** [comment]
@ashwajce Thanks for supporting the issue. I've noticed not even the cloudformation templates from AWS hands-on labs are working. I guess it must be some kind of bug on AWS. I was expecting hashicorp checking this few months ago but i still have no answer.

**Comment by ashwajce** [comment]
@jjulianprin  you can try this, This example works https://github.com/hashicorp/terraform-provider-aws/tree/master/examples/eks-getting-started

**Comment by jjulianprin** [comment]
Thanks i'll give it a shot!

**Comment by ekungurov** [comment]
Works for me, however I encountered a bit different issue. 

The nodes are not showing up inside Configuration -> Compute. They are shown inside Cluster Overview though (at least for me). Further investigation showed that this TF example is built for terraform-aws-modules/eks version 17 (outdated), and it uses 'worker_groups' in the eks-cluster.tf file. 

'worker_groups' are Self Managed Node Group. That is the reason why they are not shown as Node Group inside Configuration -> Compute (in my case). It was not so easy to figure out. 

The latest terraform-aws-modules/eks version 18.x changed terminology so it uses 'self_managed_node_groups' and 'eks_managed_node_groups' instead of 'worker_groups' and 'node_groups' (respectively). Makes it much better and more clear. This example is a bit outdated, I have to warn everyone who will stumble upon it.

**Comment by alanszlosek** [comment]
This should now be fixed by #64 and #65. Please let us know if you are still having issues.
