### ISSUE TITLE
Understanding Bastion based on the related guide

### ISSUE THREAD

**Issue by timworx** [hashicorp/learn-terraform-provision-eks-cluster#30]
The [related tutorial](https://learn.hashicorp.com/tutorials/terraform/eks) mentions setting up a bastion host:

> eks-cluster.tf provisions all the resources (AutoScaling Groups, etc...) required to set up an EKS cluster in the private subnets and bastion servers to access the cluster using the AWS EKS Module.

Looking through the guide + codebase, I don't understand this. My understanding is that a bastion host would be something like an EC2 that I would ssh into in order to access the rest of the cluster. 

Does it mean something else here? 

Also, the security groups have ingress entries for port 22 from `192.168.0.0/16` and `172.16.0.0/12`, what is the significance of these IPs? (they are not the CIDR blocks of my VPC, for example)

**Comment by Huang-W** [comment]
I don't understand the bastion host part either.

But the significance of those IP ranges is found here: [https://docs.amazonaws.cn/en_us/eks/latest/userguide/create-cluster.html](https://docs.amazonaws.cn/en_us/eks/latest/userguide/create-cluster.html)

> 
> (Optional) Choose Configure Kubernetes Service IP address range and specify a Service IPv4 range if you want to specify which CIDR block Kubernetes assigns service IP addresses from. The CIDR block must meet the following requirements:
> 
>     Within one of the following ranges: 10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16.
> 
>     Between /24 and /12.
> 
>     Doesn't overlap with any CIDR block specified in your VPC.

**Comment by Blobonat** [comment]
Any more details regarding the Bastion host? The config files do not provide any information regarding the provisioning of a Bastion host.

**Comment by BrianMMcClain** [comment]
Hey all, sorry to leave this issue around so long. I'm going through and cleaning this repo up a bit. I did some digging on this one and I also don't see any sort of bastion host ever defined in the history of this config either. I think this may have just been an error in the tutorial. We've since updated the tutorial to correct this, thank you!

On the topic of the IP ranges in the security groups, @Huang-W is correct, I believe that's that was the reasoning. This example config has also since been updated to let AWS automatically create the required security groups to remove any confusion.

Thank you!
