### ISSUE TITLE
Error: error reading IAM policy (arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy)

### ISSUE THREAD

**Issue by andreaaizza** [hashicorp/learn-terraform-provision-eks-cluster#99]
Hi,

using `aws` client with `awscli` IAM user having `AdminRestricetedRegion` (in the region of the cluster) and even after adding `AmazonEBSCSIDriverPolicy`, I get the following error while running `terraform apply`:
```
│ Error: error reading IAM policy (arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy): AccessDenied: User: arn:aws:iam::616329566558:user/awscli is not authorized to perform: iam:GetPolicy on resource: policy arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy because no identity-based policy allows the iam:GetPolicy action
│       status code: 403, request id: bbdde347-180f-48ea-968f-164509962d77
│ 
│   with data.aws_iam_policy.ebs_csi_policy,
│   on main.tf line 87, in data "aws_iam_policy" "ebs_csi_policy":
│   87: data "aws_iam_policy" "ebs_csi_policy" {
```
Can anybody help to solve it?

Regards,
Andrea

**Comment by BrianMMcClain** [comment]
Hi @andreaaizza! Sorry for the delay getting back on this one. If I understand your IAM policy correctly, is this using the `aws:RequestedRegion` condition? If so, I _believe_ this may be due to the fact that the IAM service only has one endpoint as per the [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-requestedregion).

> Some global services, such as IAM, have a single endpoint. Because this endpoint is physically located in the US East (N. Virginia) Region, IAM calls are always made to the us-east-1 Region. For example, if you create a policy that denies access to all services if the requested Region is not us-west-2, then IAM calls always fail.

There seems to be a few ways to address this. One example would be to add global IAM permissions to your policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestedRegion": "us-east-2"
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*"
        }
    ]
}
```

You can scope down the first statement more if needed as well, but that will let you deploy resources to the requested region (in this case, us-east-2) while still accessing the IAM service to create and attach policies.

AWS also mentions being able to work around this using [NotAction with Deny](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notaction.html). I'm admittedly not as familiar with this, however it looks like a policy like the following might be what they're suggesting:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:*",
                "logs:*",
                "sts:*",
                "eks:*",
                "kms:*",
                "iam:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Deny",
            "NotAction": "iam:*",
            "Resource": "*",
            "Condition": {
                "StringNotEquals": {
                    "aws:RequestedRegion": "us-east-2"
                }
            }
        }
    ]
}
```

In this case, I've scoped down the `Allow` statement to just those needed for the tutorial, but they're allowed in _all_ regions. The `Deny` statement then says "deny requests to all services except IAM if they are to a region other than us-east-2", effectively giving you us-east-2 access to the required services and global access to IAM.  

I'm not sure the particular restrictions in your scenario, but hopefully this helps!
